export const chartData = [
    {
        date: '2024-12-01',
        mood: 'happy',
        id: 1,
        amount: 439,
        memo: 'It was a good day',
    },
    {
        date: '2024-12-01',
        mood: 'sad',
        id: 2,
        amount: 380,
        memo: 'It was a good day',
    },
    {
        date: '2024-12-01',
        mood: 'excited',
        id: 3,
        amount: 200,
        memo: 'It was a good day',
    },
    {
        date: '2024-12-02',
        mood: 'happy',
        id: 1,
        amount: 88,
        memo: 'A calm and uneventful day.',
    },
    {
        date: '2024-12-02',
        mood: 'sad',
        id: 2,
        amount: 140,
        memo: 'A calm and uneventful day.',
    },
    {
        date: '2024-12-02',
        mood: 'excited',
        id: 3,
        amount: 100,
        memo: 'A calm and uneventful day.',
    },
    {
        date: '2024-12-03',
        mood: 'happy',
        id: 1,
        amount: 294,
        memo: 'The weather was pleasant.',
    },
    {
        date: '2024-12-03',
        mood: 'sad',
        id: 2,
        amount: 250,
        memo: 'The weather was pleasant.',
    },
    {
        date: '2024-12-03',
        mood: 'excited',
        id: 3,
        amount: 150,
        memo: 'The weather was pleasant.',
    },
    {
        date: '2024-12-04',
        mood: 'happy',
        id: 1,
        amount: 323,
        memo: 'A mix of emotions today.',
    },
    {
        date: '2024-12-04',
        mood: 'sad',
        id: 2,
        amount: 370,
        memo: 'A mix of emotions today.',
    },
    {
        date: '2024-12-04',
        mood: 'excited',
        id: 3,
        amount: 180,
        memo: 'A mix of emotions today.',
    },
    {
        date: '2024-12-05',
        mood: 'happy',
        id: 1,
        amount: 385,
        memo: 'Had a productive day.',
    },
    {
        date: '2024-12-05',
        mood: 'sad',
        id: 2,
        amount: 320,
        memo: 'Had a productive day.',
    },
    {
        date: '2024-12-05',
        mood: 'excited',
        id: 3,
        amount: 210,
        memo: 'Had a productive day.',
    },
    {
        date: '2024-12-06',
        mood: 'happy',
        id: 1,
        amount: 438,
        memo: 'An intense and emotional day.',
    },
    {
        date: '2024-12-06',
        mood: 'sad',
        id: 2,
        amount: 480,
        memo: 'An intense and emotional day.',
    },
    {
        date: '2024-12-06',
        mood: 'excited',
        id: 3,
        amount: 220,
        memo: 'An intense and emotional day.',
    },
    {
        date: '2024-12-07',
        mood: 'happy',
        id: 1,
        amount: 155,
        memo: 'Felt a bit low today.',
    },
    {
        date: '2024-12-07',
        mood: 'sad',
        id: 2,
        amount: 200,
        memo: 'Felt a bit low today.',
    },
    {
        date: '2024-12-07',
        mood: 'excited',
        id: 3,
        amount: 130,
        memo: 'Felt a bit low today.',
    },
    {
        date: '2024-12-08',
        mood: 'happy',
        id: 1,
        amount: 92,
        memo: 'Quiet moments of reflection.',
    },
    {
        date: '2024-12-08',
        mood: 'sad',
        id: 2,
        amount: 150,
        memo: 'Quiet moments of reflection.',
    },
    {
        date: '2024-12-08',
        mood: 'excited',
        id: 3,
        amount: 90,
        memo: 'Quiet moments of reflection.',
    },
    {
        date: '2024-12-09',
        mood: 'happy',
        id: 1,
        amount: 492,
        memo: 'Everything went smoothly.',
    },
    {
        date: '2024-12-09',
        mood: 'sad',
        id: 2,
        amount: 420,
        memo: 'Everything went smoothly.',
    },
    {
        date: '2024-12-09',
        mood: 'excited',
        id: 3,
        amount: 250,
        memo: 'Everything went smoothly.',
    },
    {
        date: '2024-12-10',
        mood: 'happy',
        id: 1,
        amount: 81,
        memo: 'A challenging day overall.',
    },
    {
        date: '2024-12-10',
        mood: 'sad',
        id: 2,
        amount: 130,
        memo: 'A challenging day overall.',
    },
    {
        date: '2024-12-10',
        mood: 'excited',
        id: 3,
        amount: 70,
        memo: 'A challenging day overall.',
    },
    {
        date: '2024-12-11',
        mood: 'sad',
        id: 2,
        amount: 380,
        memo: 'Focused on work.',
    },
    {
        date: '2024-12-11',
        mood: 'excited',
        id: 3,
        amount: 240,
        memo: 'Focused on work.',
    },
];
