export const MoodMockData = [
    {
        date: '2024-12-01',
        mood: '기쁜날',
        id: '1',
        price: 439,
        description: '좋은 하루였다.',
    },
    {
        date: '2024-12-01',
        mood: '슬픈날',
        id: '2',
        price: 380,
        description: '좋은 하루였다.',
    },
    {
        date: '2024-12-01',
        mood: '화난날',
        id: '3',
        price: 200,
        description: '좋은 하루였다.',
    },
    {
        date: '2024-12-02',
        mood: '기쁜날',
        id: '1',
        price: 88,
        description: '조용하고 평온한 하루였다.',
    },
    {
        date: '2024-12-02',
        mood: '슬픈날',
        id: '2',
        price: 140,
        description: '조용하고 평온한 하루였다.',
    },
    {
        date: '2024-12-02',
        mood: '화난날',
        id: '3',
        price: 100,
        description: '조용하고 평온한 하루였다.',
    },
    {
        date: '2024-12-03',
        mood: '기쁜날',
        id: '1',
        price: 294,
        description: '날씨가 좋았다.',
    },
    {
        date: '2024-12-03',
        mood: '슬픈날',
        id: '2',
        price: 250,
        description: '날씨가 좋았다.',
    },
    {
        date: '2024-12-03',
        mood: '화난날',
        id: '3',
        price: 150,
        description: '날씨가 좋았다.',
    },
    {
        date: '2024-12-04',
        mood: '기쁜날',
        id: '1',
        price: 323,
        description: '감정이 복잡한 하루였다.',
    },
    {
        date: '2024-12-04',
        mood: '슬픈날',
        id: '2',
        price: 370,
        description: '감정이 복잡한 하루였다.',
    },
    {
        date: '2024-12-04',
        mood: '화난날',
        id: '3',
        price: 180,
        description: '감정이 복잡한 하루였다.',
    },
    {
        date: '2024-12-05',
        mood: '기쁜날',
        id: '1',
        price: 385,
        description: '생산적인 하루였다.',
    },
    {
        date: '2024-12-05',
        mood: '슬픈날',
        id: '2',
        price: 320,
        description: '생산적인 하루였다.',
    },
    {
        date: '2024-12-05',
        mood: '화난날',
        id: '3',
        price: 210,
        description: '생산적인 하루였다.',
    },
    {
        date: '2024-12-06',
        mood: '기쁜날',
        id: '1',
        price: 438,
        description: '강렬하고 감정적인 하루였다.',
    },
    {
        date: '2024-12-06',
        mood: '슬픈날',
        id: '2',
        price: 480,
        description: '강렬하고 감정적인 하루였다.',
    },
    {
        date: '2024-12-06',
        mood: '화난날',
        id: '3',
        price: 220,
        description: '강렬하고 감정적인 하루였다.',
    },
    {
        date: '2024-12-07',
        mood: '기쁜날',
        id: '1',
        price: 155,
        description: '기운이 조금 떨어졌다.',
    },
    {
        date: '2024-12-07',
        mood: '슬픈날',
        id: '2',
        price: 200,
        description: '기운이 조금 떨어졌다.',
    },
    {
        date: '2024-12-07',
        mood: '화난날',
        id: '3',
        price: 130,
        description: '기운이 조금 떨어졌다.',
    },
    {
        date: '2024-12-08',
        mood: '기쁜날',
        id: '1',
        price: 92,
        description: '조용히 되돌아보는 시간이었다.',
    },
    {
        date: '2024-12-08',
        mood: '슬픈날',
        id: '2',
        price: 150,
        description: '조용히 되돌아보는 시간이었다.',
    },
    {
        date: '2024-12-08',
        mood: '화난날',
        id: '3',
        price: 90,
        description: '조용히 되돌아보는 시간이었다.',
    },
    {
        date: '2024-12-09',
        mood: '기쁜날',
        id: '1',
        price: 492,
        description: '모든 것이 순조로웠다.',
    },
    {
        date: '2024-12-09',
        mood: '슬픈날',
        id: '2',
        price: 420,
        description: '모든 것이 순조로웠다.',
    },
    {
        date: '2024-12-09',
        mood: '화난날',
        id: '3',
        price: 250,
        description: '모든 것이 순조로웠다.',
    },
    {
        date: '2024-12-10',
        mood: '기쁜날',
        id: '1',
        price: 81,
        description: '전반적으로 도전적인 하루였다.',
    },
    {
        date: '2024-12-10',
        mood: '슬픈날',
        id: '2',
        price: 130,
        description: '전반적으로 도전적인 하루였다.',
    },
    {
        date: '2024-12-10',
        mood: '화난날',
        id: '3',
        price: 70,
        description: '전반적으로 도전적인 하루였다.',
    },
    {
        date: '2024-12-11',
        mood: '슬픈날',
        id: '2',
        price: 380,
        description: '일에 집중한 하루였다.',
    },
    {
        date: '2024-12-11',
        mood: '화난날',
        id: '3',
        price: 240,
        description: '일에 집중한 하루였다.',
    },
];
